namespace vista
{
    partial class Form1
    {
        /// <summary>
        /// Variable del diseñador necesaria.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Limpiar los recursos que se estén usando.
        /// </summary>
        /// <param name="disposing">true si los recursos administrados se deben desechar; false en caso contrario.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Código generado por el Diseñador de Windows Forms

        /// <summary>
        /// Método necesario para admitir el Diseñador. No se puede modificar
        /// el contenido de este método con el editor de código.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.materialTabControl1 = new MaterialSkin.Controls.MaterialTabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.materialCard1 = new MaterialSkin.Controls.MaterialCard();
            this.bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.PassUserlog = new Bunifu.UI.WinForms.BunifuTextBox();
            this.CorreoUserLog = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.materialCard2 = new MaterialSkin.Controls.MaterialCard();
            this.NombreTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Apellido1Txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Apellido2Txt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.CorreoTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.PassTxt = new Bunifu.UI.WinForms.BunifuTextBox();
            this.GeneroCom = new MaterialSkin.Controls.MaterialComboBox();
            this.bunifuButton22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButton23 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.materialTabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.materialCard1.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.tabPage2.SuspendLayout();
            this.materialCard2.SuspendLayout();
            this.SuspendLayout();
            // 
            // materialTabControl1
            // 
            this.materialTabControl1.Controls.Add(this.tabPage1);
            this.materialTabControl1.Controls.Add(this.tabPage2);
            this.materialTabControl1.Depth = 0;
            this.materialTabControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.materialTabControl1.Location = new System.Drawing.Point(3, 64);
            this.materialTabControl1.MouseState = MaterialSkin.MouseState.HOVER;
            this.materialTabControl1.Multiline = true;
            this.materialTabControl1.Name = "materialTabControl1";
            this.materialTabControl1.SelectedIndex = 0;
            this.materialTabControl1.Size = new System.Drawing.Size(1137, 698);
            this.materialTabControl1.TabIndex = 0;
            // 
            // tabPage1
            // 
            this.tabPage1.Controls.Add(this.materialCard1);
            this.tabPage1.Controls.Add(this.bunifuPanel1);
            this.tabPage1.Location = new System.Drawing.Point(4, 22);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(1129, 672);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "iniciar Secion ";
            this.tabPage1.UseVisualStyleBackColor = true;
            // 
            // materialCard1
            // 
            this.materialCard1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.materialCard1.Controls.Add(this.bunifuButton21);
            this.materialCard1.Controls.Add(this.bunifuLabel1);
            this.materialCard1.Controls.Add(this.PassUserlog);
            this.materialCard1.Controls.Add(this.CorreoUserLog);
            this.materialCard1.Depth = 0;
            this.materialCard1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.materialCard1.Location = new System.Drawing.Point(545, 6);
            this.materialCard1.Margin = new System.Windows.Forms.Padding(14);
            this.materialCard1.MouseState = MaterialSkin.MouseState.HOVER;
            this.materialCard1.Name = "materialCard1";
            this.materialCard1.Padding = new System.Windows.Forms.Padding(14);
            this.materialCard1.Size = new System.Drawing.Size(578, 656);
            this.materialCard1.TabIndex = 1;
            // 
            // bunifuButton21
            // 
            this.bunifuButton21.AllowAnimations = true;
            this.bunifuButton21.AllowMouseEffects = true;
            this.bunifuButton21.AllowToggling = false;
            this.bunifuButton21.AnimationSpeed = 200;
            this.bunifuButton21.AutoGenerateColors = false;
            this.bunifuButton21.AutoRoundBorders = true;
            this.bunifuButton21.AutoSizeLeftIcon = true;
            this.bunifuButton21.AutoSizeRightIcon = true;
            this.bunifuButton21.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackColor1 = System.Drawing.Color.DeepPink;
            this.bunifuButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.BackgroundImage")));
            this.bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Dash;
            this.bunifuButton21.ButtonText = "Iniciar Secion";
            this.bunifuButton21.ButtonTextMarginLeft = 0;
            this.bunifuButton21.ColorContrastOnClick = 45;
            this.bunifuButton21.ColorContrastOnHover = 45;
            this.bunifuButton21.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton21.CustomizableEdges = borderEdges1;
            this.bunifuButton21.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton21.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton21.Font = new System.Drawing.Font("Roboto Medium", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton21.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton21.IconMarginLeft = 11;
            this.bunifuButton21.IconPadding = 10;
            this.bunifuButton21.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton21.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton21.IconSize = 25;
            this.bunifuButton21.IdleBorderColor = System.Drawing.Color.MediumVioletRed;
            this.bunifuButton21.IdleBorderRadius = 59;
            this.bunifuButton21.IdleBorderThickness = 2;
            this.bunifuButton21.IdleFillColor = System.Drawing.Color.DeepPink;
            this.bunifuButton21.IdleIconLeftImage = null;
            this.bunifuButton21.IdleIconRightImage = null;
            this.bunifuButton21.IndicateFocus = false;
            this.bunifuButton21.Location = new System.Drawing.Point(179, 472);
            this.bunifuButton21.Name = "bunifuButton21";
            this.bunifuButton21.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.OnDisabledState.BorderRadius = 30;
            this.bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnDisabledState.BorderThickness = 2;
            this.bunifuButton21.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.OnDisabledState.IconLeftImage = null;
            this.bunifuButton21.OnDisabledState.IconRightImage = null;
            this.bunifuButton21.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton21.onHoverState.BorderRadius = 30;
            this.bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.onHoverState.BorderThickness = 2;
            this.bunifuButton21.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton21.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.onHoverState.IconLeftImage = null;
            this.bunifuButton21.onHoverState.IconRightImage = null;
            this.bunifuButton21.OnIdleState.BorderColor = System.Drawing.Color.MediumVioletRed;
            this.bunifuButton21.OnIdleState.BorderRadius = 30;
            this.bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Dash;
            this.bunifuButton21.OnIdleState.BorderThickness = 2;
            this.bunifuButton21.OnIdleState.FillColor = System.Drawing.Color.DeepPink;
            this.bunifuButton21.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnIdleState.IconLeftImage = null;
            this.bunifuButton21.OnIdleState.IconRightImage = null;
            this.bunifuButton21.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.BorderRadius = 30;
            this.bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnPressedState.BorderThickness = 2;
            this.bunifuButton21.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnPressedState.IconLeftImage = null;
            this.bunifuButton21.OnPressedState.IconRightImage = null;
            this.bunifuButton21.Size = new System.Drawing.Size(220, 63);
            this.bunifuButton21.TabIndex = 3;
            this.bunifuButton21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton21.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton21.TextMarginLeft = 0;
            this.bunifuButton21.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton21.UseDefaultRadiusAndThickness = true;
            this.bunifuButton21.Click += new System.EventHandler(this.bunifuButton21_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.AutoSize = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Roboto Medium", 14.25F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.RoyalBlue;
            this.bunifuLabel1.Location = new System.Drawing.Point(44, 135);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(490, 39);
            this.bunifuLabel1.TabIndex = 2;
            this.bunifuLabel1.Text = "Inicio De Secion Administrativo";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // PassUserlog
            // 
            this.PassUserlog.AcceptsReturn = false;
            this.PassUserlog.AcceptsTab = false;
            this.PassUserlog.AllowDrop = true;
            this.PassUserlog.AnimationSpeed = 200;
            this.PassUserlog.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.PassUserlog.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.PassUserlog.AutoSizeHeight = true;
            this.PassUserlog.BackColor = System.Drawing.Color.Transparent;
            this.PassUserlog.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PassUserlog.BackgroundImage")));
            this.PassUserlog.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.PassUserlog.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PassUserlog.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PassUserlog.BorderColorIdle = System.Drawing.Color.Black;
            this.PassUserlog.BorderRadius = 20;
            this.PassUserlog.BorderThickness = 1;
            this.PassUserlog.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.PassUserlog.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.PassUserlog.DefaultFont = new System.Drawing.Font("Roboto", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.PassUserlog.DefaultText = "";
            this.PassUserlog.FillColor = System.Drawing.Color.White;
            this.PassUserlog.ForeColor = System.Drawing.Color.RoyalBlue;
            this.PassUserlog.HideSelection = true;
            this.PassUserlog.IconLeft = null;
            this.PassUserlog.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.PassUserlog.IconPadding = 10;
            this.PassUserlog.IconRight = null;
            this.PassUserlog.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.PassUserlog.Lines = new string[0];
            this.PassUserlog.Location = new System.Drawing.Point(17, 361);
            this.PassUserlog.MaxLength = 32767;
            this.PassUserlog.MinimumSize = new System.Drawing.Size(1, 1);
            this.PassUserlog.Modified = false;
            this.PassUserlog.Multiline = false;
            this.PassUserlog.Name = "PassUserlog";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PassUserlog.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.PassUserlog.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PassUserlog.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Black;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.RoyalBlue;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PassUserlog.OnIdleState = stateProperties4;
            this.PassUserlog.Padding = new System.Windows.Forms.Padding(3);
            this.PassUserlog.PasswordChar = '#';
            this.PassUserlog.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.PassUserlog.PlaceholderText = "Correo Administrativo";
            this.PassUserlog.ReadOnly = false;
            this.PassUserlog.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.PassUserlog.SelectedText = "";
            this.PassUserlog.SelectionLength = 0;
            this.PassUserlog.SelectionStart = 0;
            this.PassUserlog.ShortcutsEnabled = true;
            this.PassUserlog.Size = new System.Drawing.Size(544, 48);
            this.PassUserlog.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.PassUserlog.TabIndex = 1;
            this.PassUserlog.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.PassUserlog.TextMarginBottom = 0;
            this.PassUserlog.TextMarginLeft = 3;
            this.PassUserlog.TextMarginTop = 1;
            this.PassUserlog.TextPlaceholder = "Correo Administrativo";
            this.PassUserlog.UseSystemPasswordChar = false;
            this.PassUserlog.WordWrap = true;
            // 
            // CorreoUserLog
            // 
            this.CorreoUserLog.AcceptsReturn = false;
            this.CorreoUserLog.AcceptsTab = false;
            this.CorreoUserLog.AnimationSpeed = 200;
            this.CorreoUserLog.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.CorreoUserLog.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.CorreoUserLog.AutoSizeHeight = true;
            this.CorreoUserLog.BackColor = System.Drawing.Color.Transparent;
            this.CorreoUserLog.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CorreoUserLog.BackgroundImage")));
            this.CorreoUserLog.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.CorreoUserLog.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CorreoUserLog.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CorreoUserLog.BorderColorIdle = System.Drawing.Color.Black;
            this.CorreoUserLog.BorderRadius = 20;
            this.CorreoUserLog.BorderThickness = 1;
            this.CorreoUserLog.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.CorreoUserLog.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.CorreoUserLog.DefaultFont = new System.Drawing.Font("Roboto", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.CorreoUserLog.DefaultText = "";
            this.CorreoUserLog.FillColor = System.Drawing.Color.White;
            this.CorreoUserLog.ForeColor = System.Drawing.Color.RoyalBlue;
            this.CorreoUserLog.HideSelection = true;
            this.CorreoUserLog.IconLeft = null;
            this.CorreoUserLog.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.CorreoUserLog.IconPadding = 10;
            this.CorreoUserLog.IconRight = null;
            this.CorreoUserLog.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.CorreoUserLog.Lines = new string[0];
            this.CorreoUserLog.Location = new System.Drawing.Point(17, 271);
            this.CorreoUserLog.MaxLength = 32767;
            this.CorreoUserLog.MinimumSize = new System.Drawing.Size(1, 1);
            this.CorreoUserLog.Modified = false;
            this.CorreoUserLog.Multiline = false;
            this.CorreoUserLog.Name = "CorreoUserLog";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CorreoUserLog.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.CorreoUserLog.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CorreoUserLog.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Black;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.RoyalBlue;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CorreoUserLog.OnIdleState = stateProperties8;
            this.CorreoUserLog.Padding = new System.Windows.Forms.Padding(3);
            this.CorreoUserLog.PasswordChar = '\0';
            this.CorreoUserLog.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.CorreoUserLog.PlaceholderText = "Correo Administrativo";
            this.CorreoUserLog.ReadOnly = false;
            this.CorreoUserLog.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.CorreoUserLog.SelectedText = "";
            this.CorreoUserLog.SelectionLength = 0;
            this.CorreoUserLog.SelectionStart = 0;
            this.CorreoUserLog.ShortcutsEnabled = true;
            this.CorreoUserLog.Size = new System.Drawing.Size(544, 48);
            this.CorreoUserLog.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.CorreoUserLog.TabIndex = 0;
            this.CorreoUserLog.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.CorreoUserLog.TextMarginBottom = 0;
            this.CorreoUserLog.TextMarginLeft = 3;
            this.CorreoUserLog.TextMarginTop = 1;
            this.CorreoUserLog.TextPlaceholder = "Correo Administrativo";
            this.CorreoUserLog.UseSystemPasswordChar = false;
            this.CorreoUserLog.WordWrap = true;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.RoyalBlue;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 3;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.pictureBox1);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuPanel1.Location = new System.Drawing.Point(3, 3);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(537, 666);
            this.bunifuPanel1.TabIndex = 0;
            this.bunifuPanel1.Click += new System.EventHandler(this.bunifuPanel1_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pictureBox1.Image = global::vista.Properties.Resources._2150171042;
            this.pictureBox1.Location = new System.Drawing.Point(0, 0);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(537, 666);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 0;
            this.pictureBox1.TabStop = false;
            // 
            // tabPage2
            // 
            this.tabPage2.Controls.Add(this.materialCard2);
            this.tabPage2.Location = new System.Drawing.Point(4, 22);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(1129, 672);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "Crear Usuario";
            this.tabPage2.UseVisualStyleBackColor = true;
            // 
            // materialCard2
            // 
            this.materialCard2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.materialCard2.Controls.Add(this.bunifuLabel2);
            this.materialCard2.Controls.Add(this.bunifuButton23);
            this.materialCard2.Controls.Add(this.bunifuButton22);
            this.materialCard2.Controls.Add(this.GeneroCom);
            this.materialCard2.Controls.Add(this.PassTxt);
            this.materialCard2.Controls.Add(this.CorreoTxt);
            this.materialCard2.Controls.Add(this.Apellido2Txt);
            this.materialCard2.Controls.Add(this.Apellido1Txt);
            this.materialCard2.Controls.Add(this.NombreTxt);
            this.materialCard2.Depth = 0;
            this.materialCard2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.materialCard2.Location = new System.Drawing.Point(202, 16);
            this.materialCard2.Margin = new System.Windows.Forms.Padding(14);
            this.materialCard2.MouseState = MaterialSkin.MouseState.HOVER;
            this.materialCard2.Name = "materialCard2";
            this.materialCard2.Padding = new System.Windows.Forms.Padding(14);
            this.materialCard2.Size = new System.Drawing.Size(725, 641);
            this.materialCard2.TabIndex = 0;
            // 
            // NombreTxt
            // 
            this.NombreTxt.AcceptsReturn = false;
            this.NombreTxt.AcceptsTab = false;
            this.NombreTxt.AnimationSpeed = 200;
            this.NombreTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.NombreTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.NombreTxt.AutoSizeHeight = true;
            this.NombreTxt.BackColor = System.Drawing.Color.Transparent;
            this.NombreTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("NombreTxt.BackgroundImage")));
            this.NombreTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.NombreTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.NombreTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.NombreTxt.BorderColorIdle = System.Drawing.Color.Black;
            this.NombreTxt.BorderRadius = 20;
            this.NombreTxt.BorderThickness = 1;
            this.NombreTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.NombreTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.NombreTxt.DefaultFont = new System.Drawing.Font("Roboto", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.NombreTxt.DefaultText = "";
            this.NombreTxt.FillColor = System.Drawing.Color.White;
            this.NombreTxt.ForeColor = System.Drawing.Color.RoyalBlue;
            this.NombreTxt.HideSelection = true;
            this.NombreTxt.IconLeft = null;
            this.NombreTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.NombreTxt.IconPadding = 10;
            this.NombreTxt.IconRight = null;
            this.NombreTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.NombreTxt.Lines = new string[0];
            this.NombreTxt.Location = new System.Drawing.Point(90, 83);
            this.NombreTxt.MaxLength = 32767;
            this.NombreTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.NombreTxt.Modified = false;
            this.NombreTxt.Multiline = false;
            this.NombreTxt.Name = "NombreTxt";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NombreTxt.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.NombreTxt.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NombreTxt.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Black;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.RoyalBlue;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.NombreTxt.OnIdleState = stateProperties28;
            this.NombreTxt.Padding = new System.Windows.Forms.Padding(3);
            this.NombreTxt.PasswordChar = '\0';
            this.NombreTxt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.NombreTxt.PlaceholderText = "Nombre";
            this.NombreTxt.ReadOnly = false;
            this.NombreTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.NombreTxt.SelectedText = "";
            this.NombreTxt.SelectionLength = 0;
            this.NombreTxt.SelectionStart = 0;
            this.NombreTxt.ShortcutsEnabled = true;
            this.NombreTxt.Size = new System.Drawing.Size(544, 48);
            this.NombreTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.NombreTxt.TabIndex = 1;
            this.NombreTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.NombreTxt.TextMarginBottom = 0;
            this.NombreTxt.TextMarginLeft = 3;
            this.NombreTxt.TextMarginTop = 1;
            this.NombreTxt.TextPlaceholder = "Nombre";
            this.NombreTxt.UseSystemPasswordChar = false;
            this.NombreTxt.WordWrap = true;
            // 
            // Apellido1Txt
            // 
            this.Apellido1Txt.AcceptsReturn = false;
            this.Apellido1Txt.AcceptsTab = false;
            this.Apellido1Txt.AnimationSpeed = 200;
            this.Apellido1Txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Apellido1Txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Apellido1Txt.AutoSizeHeight = true;
            this.Apellido1Txt.BackColor = System.Drawing.Color.Transparent;
            this.Apellido1Txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Apellido1Txt.BackgroundImage")));
            this.Apellido1Txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Apellido1Txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Apellido1Txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Apellido1Txt.BorderColorIdle = System.Drawing.Color.Black;
            this.Apellido1Txt.BorderRadius = 20;
            this.Apellido1Txt.BorderThickness = 1;
            this.Apellido1Txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Apellido1Txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Apellido1Txt.DefaultFont = new System.Drawing.Font("Roboto", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Apellido1Txt.DefaultText = "";
            this.Apellido1Txt.FillColor = System.Drawing.Color.White;
            this.Apellido1Txt.ForeColor = System.Drawing.Color.RoyalBlue;
            this.Apellido1Txt.HideSelection = true;
            this.Apellido1Txt.IconLeft = null;
            this.Apellido1Txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Apellido1Txt.IconPadding = 10;
            this.Apellido1Txt.IconRight = null;
            this.Apellido1Txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Apellido1Txt.Lines = new string[0];
            this.Apellido1Txt.Location = new System.Drawing.Point(90, 164);
            this.Apellido1Txt.MaxLength = 32767;
            this.Apellido1Txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.Apellido1Txt.Modified = false;
            this.Apellido1Txt.Multiline = false;
            this.Apellido1Txt.Name = "Apellido1Txt";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Apellido1Txt.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Apellido1Txt.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Apellido1Txt.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Black;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.RoyalBlue;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Apellido1Txt.OnIdleState = stateProperties24;
            this.Apellido1Txt.Padding = new System.Windows.Forms.Padding(3);
            this.Apellido1Txt.PasswordChar = '\0';
            this.Apellido1Txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.Apellido1Txt.PlaceholderText = "Primer Apellido";
            this.Apellido1Txt.ReadOnly = false;
            this.Apellido1Txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Apellido1Txt.SelectedText = "";
            this.Apellido1Txt.SelectionLength = 0;
            this.Apellido1Txt.SelectionStart = 0;
            this.Apellido1Txt.ShortcutsEnabled = true;
            this.Apellido1Txt.Size = new System.Drawing.Size(544, 48);
            this.Apellido1Txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Apellido1Txt.TabIndex = 2;
            this.Apellido1Txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Apellido1Txt.TextMarginBottom = 0;
            this.Apellido1Txt.TextMarginLeft = 3;
            this.Apellido1Txt.TextMarginTop = 1;
            this.Apellido1Txt.TextPlaceholder = "Primer Apellido";
            this.Apellido1Txt.UseSystemPasswordChar = false;
            this.Apellido1Txt.WordWrap = true;
            // 
            // Apellido2Txt
            // 
            this.Apellido2Txt.AcceptsReturn = false;
            this.Apellido2Txt.AcceptsTab = false;
            this.Apellido2Txt.AnimationSpeed = 200;
            this.Apellido2Txt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Apellido2Txt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Apellido2Txt.AutoSizeHeight = true;
            this.Apellido2Txt.BackColor = System.Drawing.Color.Transparent;
            this.Apellido2Txt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Apellido2Txt.BackgroundImage")));
            this.Apellido2Txt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.Apellido2Txt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Apellido2Txt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Apellido2Txt.BorderColorIdle = System.Drawing.Color.Black;
            this.Apellido2Txt.BorderRadius = 20;
            this.Apellido2Txt.BorderThickness = 1;
            this.Apellido2Txt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Apellido2Txt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Apellido2Txt.DefaultFont = new System.Drawing.Font("Roboto", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Apellido2Txt.DefaultText = "";
            this.Apellido2Txt.FillColor = System.Drawing.Color.White;
            this.Apellido2Txt.ForeColor = System.Drawing.Color.RoyalBlue;
            this.Apellido2Txt.HideSelection = true;
            this.Apellido2Txt.IconLeft = null;
            this.Apellido2Txt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Apellido2Txt.IconPadding = 10;
            this.Apellido2Txt.IconRight = null;
            this.Apellido2Txt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Apellido2Txt.Lines = new string[0];
            this.Apellido2Txt.Location = new System.Drawing.Point(90, 245);
            this.Apellido2Txt.MaxLength = 32767;
            this.Apellido2Txt.MinimumSize = new System.Drawing.Size(1, 1);
            this.Apellido2Txt.Modified = false;
            this.Apellido2Txt.Multiline = false;
            this.Apellido2Txt.Name = "Apellido2Txt";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Apellido2Txt.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Apellido2Txt.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Apellido2Txt.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Black;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.RoyalBlue;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Apellido2Txt.OnIdleState = stateProperties20;
            this.Apellido2Txt.Padding = new System.Windows.Forms.Padding(3);
            this.Apellido2Txt.PasswordChar = '\0';
            this.Apellido2Txt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.Apellido2Txt.PlaceholderText = "Segundo Apellido";
            this.Apellido2Txt.ReadOnly = false;
            this.Apellido2Txt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Apellido2Txt.SelectedText = "";
            this.Apellido2Txt.SelectionLength = 0;
            this.Apellido2Txt.SelectionStart = 0;
            this.Apellido2Txt.ShortcutsEnabled = true;
            this.Apellido2Txt.Size = new System.Drawing.Size(544, 48);
            this.Apellido2Txt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Apellido2Txt.TabIndex = 3;
            this.Apellido2Txt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Apellido2Txt.TextMarginBottom = 0;
            this.Apellido2Txt.TextMarginLeft = 3;
            this.Apellido2Txt.TextMarginTop = 1;
            this.Apellido2Txt.TextPlaceholder = "Segundo Apellido";
            this.Apellido2Txt.UseSystemPasswordChar = false;
            this.Apellido2Txt.WordWrap = true;
            // 
            // CorreoTxt
            // 
            this.CorreoTxt.AcceptsReturn = false;
            this.CorreoTxt.AcceptsTab = false;
            this.CorreoTxt.AnimationSpeed = 200;
            this.CorreoTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.CorreoTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.CorreoTxt.AutoSizeHeight = true;
            this.CorreoTxt.BackColor = System.Drawing.Color.Transparent;
            this.CorreoTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CorreoTxt.BackgroundImage")));
            this.CorreoTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.CorreoTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CorreoTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CorreoTxt.BorderColorIdle = System.Drawing.Color.Black;
            this.CorreoTxt.BorderRadius = 20;
            this.CorreoTxt.BorderThickness = 1;
            this.CorreoTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.CorreoTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.CorreoTxt.DefaultFont = new System.Drawing.Font("Roboto", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.CorreoTxt.DefaultText = "";
            this.CorreoTxt.FillColor = System.Drawing.Color.White;
            this.CorreoTxt.ForeColor = System.Drawing.Color.RoyalBlue;
            this.CorreoTxt.HideSelection = true;
            this.CorreoTxt.IconLeft = null;
            this.CorreoTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.CorreoTxt.IconPadding = 10;
            this.CorreoTxt.IconRight = null;
            this.CorreoTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.CorreoTxt.Lines = new string[0];
            this.CorreoTxt.Location = new System.Drawing.Point(90, 326);
            this.CorreoTxt.MaxLength = 32767;
            this.CorreoTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.CorreoTxt.Modified = false;
            this.CorreoTxt.Multiline = false;
            this.CorreoTxt.Name = "CorreoTxt";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CorreoTxt.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.CorreoTxt.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CorreoTxt.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Black;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.RoyalBlue;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.CorreoTxt.OnIdleState = stateProperties16;
            this.CorreoTxt.Padding = new System.Windows.Forms.Padding(3);
            this.CorreoTxt.PasswordChar = '\0';
            this.CorreoTxt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.CorreoTxt.PlaceholderText = "Correo Administrativo";
            this.CorreoTxt.ReadOnly = false;
            this.CorreoTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.CorreoTxt.SelectedText = "";
            this.CorreoTxt.SelectionLength = 0;
            this.CorreoTxt.SelectionStart = 0;
            this.CorreoTxt.ShortcutsEnabled = true;
            this.CorreoTxt.Size = new System.Drawing.Size(544, 48);
            this.CorreoTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.CorreoTxt.TabIndex = 4;
            this.CorreoTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.CorreoTxt.TextMarginBottom = 0;
            this.CorreoTxt.TextMarginLeft = 3;
            this.CorreoTxt.TextMarginTop = 1;
            this.CorreoTxt.TextPlaceholder = "Correo Administrativo";
            this.CorreoTxt.UseSystemPasswordChar = false;
            this.CorreoTxt.WordWrap = true;
            // 
            // PassTxt
            // 
            this.PassTxt.AcceptsReturn = false;
            this.PassTxt.AcceptsTab = false;
            this.PassTxt.AnimationSpeed = 200;
            this.PassTxt.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.PassTxt.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.PassTxt.AutoSizeHeight = true;
            this.PassTxt.BackColor = System.Drawing.Color.Transparent;
            this.PassTxt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("PassTxt.BackgroundImage")));
            this.PassTxt.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.PassTxt.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.PassTxt.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.PassTxt.BorderColorIdle = System.Drawing.Color.Black;
            this.PassTxt.BorderRadius = 20;
            this.PassTxt.BorderThickness = 1;
            this.PassTxt.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.PassTxt.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.PassTxt.DefaultFont = new System.Drawing.Font("Roboto", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.PassTxt.DefaultText = "";
            this.PassTxt.FillColor = System.Drawing.Color.White;
            this.PassTxt.ForeColor = System.Drawing.Color.RoyalBlue;
            this.PassTxt.HideSelection = true;
            this.PassTxt.IconLeft = null;
            this.PassTxt.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.PassTxt.IconPadding = 10;
            this.PassTxt.IconRight = null;
            this.PassTxt.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.PassTxt.Lines = new string[0];
            this.PassTxt.Location = new System.Drawing.Point(90, 407);
            this.PassTxt.MaxLength = 32767;
            this.PassTxt.MinimumSize = new System.Drawing.Size(1, 1);
            this.PassTxt.Modified = false;
            this.PassTxt.Multiline = false;
            this.PassTxt.Name = "PassTxt";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PassTxt.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.PassTxt.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PassTxt.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Black;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.RoyalBlue;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.PassTxt.OnIdleState = stateProperties12;
            this.PassTxt.Padding = new System.Windows.Forms.Padding(3);
            this.PassTxt.PasswordChar = '\0';
            this.PassTxt.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.PassTxt.PlaceholderText = "Conteaseña";
            this.PassTxt.ReadOnly = false;
            this.PassTxt.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.PassTxt.SelectedText = "";
            this.PassTxt.SelectionLength = 0;
            this.PassTxt.SelectionStart = 0;
            this.PassTxt.ShortcutsEnabled = true;
            this.PassTxt.Size = new System.Drawing.Size(544, 48);
            this.PassTxt.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.PassTxt.TabIndex = 5;
            this.PassTxt.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.PassTxt.TextMarginBottom = 0;
            this.PassTxt.TextMarginLeft = 3;
            this.PassTxt.TextMarginTop = 1;
            this.PassTxt.TextPlaceholder = "Conteaseña";
            this.PassTxt.UseSystemPasswordChar = false;
            this.PassTxt.WordWrap = true;
            // 
            // GeneroCom
            // 
            this.GeneroCom.AutoResize = false;
            this.GeneroCom.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.GeneroCom.Depth = 0;
            this.GeneroCom.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawVariable;
            this.GeneroCom.DropDownHeight = 174;
            this.GeneroCom.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.GeneroCom.DropDownWidth = 121;
            this.GeneroCom.Font = new System.Drawing.Font("Roboto Medium", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.GeneroCom.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.GeneroCom.FormattingEnabled = true;
            this.GeneroCom.IntegralHeight = false;
            this.GeneroCom.ItemHeight = 43;
            this.GeneroCom.Items.AddRange(new object[] {
            "Otros",
            "Hombre",
            "Mujer"});
            this.GeneroCom.Location = new System.Drawing.Point(90, 488);
            this.GeneroCom.MaxDropDownItems = 4;
            this.GeneroCom.MouseState = MaterialSkin.MouseState.OUT;
            this.GeneroCom.Name = "GeneroCom";
            this.GeneroCom.Size = new System.Drawing.Size(544, 49);
            this.GeneroCom.StartIndex = 0;
            this.GeneroCom.TabIndex = 6;
            // 
            // bunifuButton22
            // 
            this.bunifuButton22.AllowAnimations = true;
            this.bunifuButton22.AllowMouseEffects = true;
            this.bunifuButton22.AllowToggling = false;
            this.bunifuButton22.AnimationSpeed = 200;
            this.bunifuButton22.AutoGenerateColors = false;
            this.bunifuButton22.AutoRoundBorders = true;
            this.bunifuButton22.AutoSizeLeftIcon = true;
            this.bunifuButton22.AutoSizeRightIcon = true;
            this.bunifuButton22.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.BackColor1 = System.Drawing.Color.Pink;
            this.bunifuButton22.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton22.BackgroundImage")));
            this.bunifuButton22.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.ButtonText = "Crear Usuario";
            this.bunifuButton22.ButtonTextMarginLeft = 0;
            this.bunifuButton22.ColorContrastOnClick = 45;
            this.bunifuButton22.ColorContrastOnHover = 45;
            this.bunifuButton22.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButton22.CustomizableEdges = borderEdges3;
            this.bunifuButton22.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton22.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton22.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton22.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton22.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton22.Font = new System.Drawing.Font("Roboto", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton22.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton22.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton22.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton22.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton22.IconMarginLeft = 11;
            this.bunifuButton22.IconPadding = 10;
            this.bunifuButton22.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton22.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton22.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton22.IconSize = 25;
            this.bunifuButton22.IdleBorderColor = System.Drawing.Color.Plum;
            this.bunifuButton22.IdleBorderRadius = 66;
            this.bunifuButton22.IdleBorderThickness = 1;
            this.bunifuButton22.IdleFillColor = System.Drawing.Color.Pink;
            this.bunifuButton22.IdleIconLeftImage = null;
            this.bunifuButton22.IdleIconRightImage = null;
            this.bunifuButton22.IndicateFocus = false;
            this.bunifuButton22.Location = new System.Drawing.Point(92, 558);
            this.bunifuButton22.Name = "bunifuButton22";
            this.bunifuButton22.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton22.OnDisabledState.BorderRadius = 1;
            this.bunifuButton22.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnDisabledState.BorderThickness = 1;
            this.bunifuButton22.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton22.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton22.OnDisabledState.IconLeftImage = null;
            this.bunifuButton22.OnDisabledState.IconRightImage = null;
            this.bunifuButton22.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton22.onHoverState.BorderRadius = 1;
            this.bunifuButton22.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.onHoverState.BorderThickness = 1;
            this.bunifuButton22.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton22.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.onHoverState.IconLeftImage = null;
            this.bunifuButton22.onHoverState.IconRightImage = null;
            this.bunifuButton22.OnIdleState.BorderColor = System.Drawing.Color.Plum;
            this.bunifuButton22.OnIdleState.BorderRadius = 1;
            this.bunifuButton22.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnIdleState.BorderThickness = 1;
            this.bunifuButton22.OnIdleState.FillColor = System.Drawing.Color.Pink;
            this.bunifuButton22.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton22.OnIdleState.IconLeftImage = null;
            this.bunifuButton22.OnIdleState.IconRightImage = null;
            this.bunifuButton22.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton22.OnPressedState.BorderRadius = 1;
            this.bunifuButton22.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnPressedState.BorderThickness = 1;
            this.bunifuButton22.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton22.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.OnPressedState.IconLeftImage = null;
            this.bunifuButton22.OnPressedState.IconRightImage = null;
            this.bunifuButton22.Size = new System.Drawing.Size(162, 68);
            this.bunifuButton22.TabIndex = 7;
            this.bunifuButton22.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton22.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton22.TextMarginLeft = 0;
            this.bunifuButton22.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton22.UseDefaultRadiusAndThickness = true;
            this.bunifuButton22.Click += new System.EventHandler(this.bunifuButton22_Click);
            // 
            // bunifuButton23
            // 
            this.bunifuButton23.AllowAnimations = true;
            this.bunifuButton23.AllowMouseEffects = true;
            this.bunifuButton23.AllowToggling = false;
            this.bunifuButton23.AnimationSpeed = 200;
            this.bunifuButton23.AutoGenerateColors = false;
            this.bunifuButton23.AutoRoundBorders = true;
            this.bunifuButton23.AutoSizeLeftIcon = true;
            this.bunifuButton23.AutoSizeRightIcon = true;
            this.bunifuButton23.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton23.BackColor1 = System.Drawing.Color.Teal;
            this.bunifuButton23.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton23.BackgroundImage")));
            this.bunifuButton23.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton23.ButtonText = "Limpiar Cuadros";
            this.bunifuButton23.ButtonTextMarginLeft = 0;
            this.bunifuButton23.ColorContrastOnClick = 45;
            this.bunifuButton23.ColorContrastOnHover = 45;
            this.bunifuButton23.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton23.CustomizableEdges = borderEdges2;
            this.bunifuButton23.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton23.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton23.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton23.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton23.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton23.Font = new System.Drawing.Font("Roboto", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton23.ForeColor = System.Drawing.Color.White;
            this.bunifuButton23.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton23.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton23.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton23.IconMarginLeft = 11;
            this.bunifuButton23.IconPadding = 10;
            this.bunifuButton23.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton23.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton23.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton23.IconSize = 25;
            this.bunifuButton23.IdleBorderColor = System.Drawing.Color.LightCyan;
            this.bunifuButton23.IdleBorderRadius = 66;
            this.bunifuButton23.IdleBorderThickness = 1;
            this.bunifuButton23.IdleFillColor = System.Drawing.Color.Teal;
            this.bunifuButton23.IdleIconLeftImage = null;
            this.bunifuButton23.IdleIconRightImage = null;
            this.bunifuButton23.IndicateFocus = false;
            this.bunifuButton23.Location = new System.Drawing.Point(279, 558);
            this.bunifuButton23.Name = "bunifuButton23";
            this.bunifuButton23.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton23.OnDisabledState.BorderRadius = 1;
            this.bunifuButton23.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton23.OnDisabledState.BorderThickness = 1;
            this.bunifuButton23.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton23.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton23.OnDisabledState.IconLeftImage = null;
            this.bunifuButton23.OnDisabledState.IconRightImage = null;
            this.bunifuButton23.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton23.onHoverState.BorderRadius = 1;
            this.bunifuButton23.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton23.onHoverState.BorderThickness = 1;
            this.bunifuButton23.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton23.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton23.onHoverState.IconLeftImage = null;
            this.bunifuButton23.onHoverState.IconRightImage = null;
            this.bunifuButton23.OnIdleState.BorderColor = System.Drawing.Color.LightCyan;
            this.bunifuButton23.OnIdleState.BorderRadius = 1;
            this.bunifuButton23.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton23.OnIdleState.BorderThickness = 1;
            this.bunifuButton23.OnIdleState.FillColor = System.Drawing.Color.Teal;
            this.bunifuButton23.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton23.OnIdleState.IconLeftImage = null;
            this.bunifuButton23.OnIdleState.IconRightImage = null;
            this.bunifuButton23.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton23.OnPressedState.BorderRadius = 1;
            this.bunifuButton23.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton23.OnPressedState.BorderThickness = 1;
            this.bunifuButton23.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton23.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton23.OnPressedState.IconLeftImage = null;
            this.bunifuButton23.OnPressedState.IconRightImage = null;
            this.bunifuButton23.Size = new System.Drawing.Size(162, 68);
            this.bunifuButton23.TabIndex = 8;
            this.bunifuButton23.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton23.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton23.TextMarginLeft = 0;
            this.bunifuButton23.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton23.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Roboto Medium", 18F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(62)))), ((int)(((byte)(86)))), ((int)(((byte)(183)))));
            this.bunifuLabel2.Location = new System.Drawing.Point(278, 29);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(169, 29);
            this.bunifuLabel2.TabIndex = 9;
            this.bunifuLabel2.Text = "Crear usuarios";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1143, 765);
            this.Controls.Add(this.materialTabControl1);
            this.DrawerTabControl = this.materialTabControl1;
            this.Name = "Form1";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Inicio De Secion";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.materialTabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.materialCard1.ResumeLayout(false);
            this.bunifuPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.tabPage2.ResumeLayout(false);
            this.materialCard2.ResumeLayout(false);
            this.materialCard2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private MaterialSkin.Controls.MaterialTabControl materialTabControl1;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.TabPage tabPage2;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private System.Windows.Forms.PictureBox pictureBox1;
        private MaterialSkin.Controls.MaterialCard materialCard1;
        private Bunifu.UI.WinForms.BunifuTextBox CorreoUserLog;
        private Bunifu.UI.WinForms.BunifuTextBox PassUserlog;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private MaterialSkin.Controls.MaterialCard materialCard2;
        private Bunifu.UI.WinForms.BunifuTextBox PassTxt;
        private Bunifu.UI.WinForms.BunifuTextBox CorreoTxt;
        private Bunifu.UI.WinForms.BunifuTextBox Apellido2Txt;
        private Bunifu.UI.WinForms.BunifuTextBox Apellido1Txt;
        private Bunifu.UI.WinForms.BunifuTextBox NombreTxt;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton22;
        private MaterialSkin.Controls.MaterialComboBox GeneroCom;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton23;
    }
}

