namespace vista
{
    partial class Gestion
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Gestion));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.materialTabControl1 = new MaterialSkin.Controls.MaterialTabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.materialCard1 = new MaterialSkin.Controls.MaterialCard();
            this.Empleados_G = new MaterialSkin.Controls.MaterialComboBox();
            this.Generos_G = new MaterialSkin.Controls.MaterialComboBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.MyDataUsers = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.bunifuButton3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Pass_G = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Fecha_2 = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.Fecha_1 = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.Correo_G = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Apellido_2_G = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Apellido_1_G = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Nombre_G = new Bunifu.UI.WinForms.BunifuTextBox();
            this.ID_G = new Bunifu.UI.WinForms.BunifuTextBox();
            this.materialTabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.materialCard1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.MyDataUsers)).BeginInit();
            this.SuspendLayout();
            // 
            // materialTabControl1
            // 
            this.materialTabControl1.Controls.Add(this.tabPage1);
            this.materialTabControl1.Controls.Add(this.tabPage2);
            this.materialTabControl1.Depth = 0;
            this.materialTabControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.materialTabControl1.Location = new System.Drawing.Point(3, 64);
            this.materialTabControl1.MouseState = MaterialSkin.MouseState.HOVER;
            this.materialTabControl1.Multiline = true;
            this.materialTabControl1.Name = "materialTabControl1";
            this.materialTabControl1.SelectedIndex = 0;
            this.materialTabControl1.Size = new System.Drawing.Size(1135, 921);
            this.materialTabControl1.TabIndex = 0;
            // 
            // tabPage1
            // 
            this.tabPage1.Controls.Add(this.materialCard1);
            this.tabPage1.Controls.Add(this.bunifuLabel1);
            this.tabPage1.Controls.Add(this.MyDataUsers);
            this.tabPage1.Location = new System.Drawing.Point(4, 22);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(1127, 895);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "Gestion De usuarios";
            this.tabPage1.UseVisualStyleBackColor = true;
            this.tabPage1.Click += new System.EventHandler(this.tabPage1_Click);
            // 
            // materialCard1
            // 
            this.materialCard1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.materialCard1.Controls.Add(this.bunifuButton3);
            this.materialCard1.Controls.Add(this.bunifuButton2);
            this.materialCard1.Controls.Add(this.bunifuButton1);
            this.materialCard1.Controls.Add(this.Pass_G);
            this.materialCard1.Controls.Add(this.Fecha_2);
            this.materialCard1.Controls.Add(this.Fecha_1);
            this.materialCard1.Controls.Add(this.Empleados_G);
            this.materialCard1.Controls.Add(this.Generos_G);
            this.materialCard1.Controls.Add(this.Correo_G);
            this.materialCard1.Controls.Add(this.Apellido_2_G);
            this.materialCard1.Controls.Add(this.Apellido_1_G);
            this.materialCard1.Controls.Add(this.Nombre_G);
            this.materialCard1.Controls.Add(this.ID_G);
            this.materialCard1.Depth = 0;
            this.materialCard1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.materialCard1.Location = new System.Drawing.Point(10, 69);
            this.materialCard1.Margin = new System.Windows.Forms.Padding(14);
            this.materialCard1.MouseState = MaterialSkin.MouseState.HOVER;
            this.materialCard1.Name = "materialCard1";
            this.materialCard1.Padding = new System.Windows.Forms.Padding(14);
            this.materialCard1.Size = new System.Drawing.Size(1107, 422);
            this.materialCard1.TabIndex = 3;
            this.materialCard1.Paint += new System.Windows.Forms.PaintEventHandler(this.materialCard1_Paint);
            // 
            // Empleados_G
            // 
            this.Empleados_G.AutoResize = false;
            this.Empleados_G.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Empleados_G.Depth = 0;
            this.Empleados_G.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawVariable;
            this.Empleados_G.DropDownHeight = 174;
            this.Empleados_G.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.Empleados_G.DropDownWidth = 121;
            this.Empleados_G.Font = new System.Drawing.Font("Roboto Medium", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.Empleados_G.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.Empleados_G.FormattingEnabled = true;
            this.Empleados_G.IntegralHeight = false;
            this.Empleados_G.ItemHeight = 43;
            this.Empleados_G.Items.AddRange(new object[] {
            "Empleado",
            "Cliente"});
            this.Empleados_G.Location = new System.Drawing.Point(774, 207);
            this.Empleados_G.MaxDropDownItems = 4;
            this.Empleados_G.MouseState = MaterialSkin.MouseState.OUT;
            this.Empleados_G.Name = "Empleados_G";
            this.Empleados_G.Size = new System.Drawing.Size(290, 49);
            this.Empleados_G.StartIndex = 0;
            this.Empleados_G.TabIndex = 20;
            // 
            // Generos_G
            // 
            this.Generos_G.AutoResize = false;
            this.Generos_G.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.Generos_G.Depth = 0;
            this.Generos_G.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawVariable;
            this.Generos_G.DropDownHeight = 174;
            this.Generos_G.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.Generos_G.DropDownWidth = 121;
            this.Generos_G.Font = new System.Drawing.Font("Roboto Medium", 14F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Pixel);
            this.Generos_G.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.Generos_G.FormattingEnabled = true;
            this.Generos_G.IntegralHeight = false;
            this.Generos_G.ItemHeight = 43;
            this.Generos_G.Items.AddRange(new object[] {
            "Hombre",
            "Mujer ",
            "Otro"});
            this.Generos_G.Location = new System.Drawing.Point(425, 281);
            this.Generos_G.MaxDropDownItems = 4;
            this.Generos_G.MouseState = MaterialSkin.MouseState.OUT;
            this.Generos_G.Name = "Generos_G";
            this.Generos_G.Size = new System.Drawing.Size(290, 49);
            this.Generos_G.StartIndex = 0;
            this.Generos_G.TabIndex = 19;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Roboto", 18F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.SystemColors.HotTrack;
            this.bunifuLabel1.Location = new System.Drawing.Point(454, 23);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(218, 29);
            this.bunifuLabel1.TabIndex = 2;
            this.bunifuLabel1.Text = "Gestion De Usuarios";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel1.Click += new System.EventHandler(this.bunifuLabel1_Click);
            // 
            // MyDataUsers
            // 
            this.MyDataUsers.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.MyDataUsers.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.MyDataUsers.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.MyDataUsers.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.MyDataUsers.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.MyDataUsers.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.MyDataUsers.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.MyDataUsers.ColumnHeadersHeight = 40;
            this.MyDataUsers.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.MyDataUsers.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.MyDataUsers.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.MyDataUsers.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.MyDataUsers.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.MyDataUsers.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.MyDataUsers.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.MyDataUsers.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.MyDataUsers.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.MyDataUsers.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.MyDataUsers.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.MyDataUsers.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.MyDataUsers.CurrentTheme.Name = null;
            this.MyDataUsers.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.MyDataUsers.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.MyDataUsers.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.MyDataUsers.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.MyDataUsers.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.MyDataUsers.DefaultCellStyle = dataGridViewCellStyle3;
            this.MyDataUsers.EnableHeadersVisualStyles = false;
            this.MyDataUsers.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.MyDataUsers.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.MyDataUsers.HeaderBgColor = System.Drawing.Color.Empty;
            this.MyDataUsers.HeaderForeColor = System.Drawing.Color.White;
            this.MyDataUsers.Location = new System.Drawing.Point(9, 519);
            this.MyDataUsers.Name = "MyDataUsers";
            this.MyDataUsers.RowHeadersVisible = false;
            this.MyDataUsers.RowTemplate.Height = 40;
            this.MyDataUsers.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.MyDataUsers.Size = new System.Drawing.Size(1108, 370);
            this.MyDataUsers.TabIndex = 0;
            this.MyDataUsers.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.MyDataUsers.DataError += new System.Windows.Forms.DataGridViewDataErrorEventHandler(this.MyDataUsers_DataError);
            // 
            // tabPage2
            // 
            this.tabPage2.Location = new System.Drawing.Point(4, 22);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(1127, 895);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "tabPage2";
            this.tabPage2.UseVisualStyleBackColor = true;
            // 
            // bunifuButton3
            // 
            this.bunifuButton3.AllowAnimations = true;
            this.bunifuButton3.AllowMouseEffects = true;
            this.bunifuButton3.AllowToggling = false;
            this.bunifuButton3.AnimationSpeed = 200;
            this.bunifuButton3.AutoGenerateColors = false;
            this.bunifuButton3.AutoRoundBorders = false;
            this.bunifuButton3.AutoSizeLeftIcon = true;
            this.bunifuButton3.AutoSizeRightIcon = true;
            this.bunifuButton3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.BackgroundImage")));
            this.bunifuButton3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.ButtonText = "Actualizar";
            this.bunifuButton3.ButtonTextMarginLeft = 0;
            this.bunifuButton3.ColorContrastOnClick = 45;
            this.bunifuButton3.ColorContrastOnHover = 45;
            this.bunifuButton3.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton3.CustomizableEdges = borderEdges1;
            this.bunifuButton3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton3.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton3.Font = new System.Drawing.Font("Roboto", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton3.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton3.IconLeft = null;
            this.bunifuButton3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton3.IconMarginLeft = 11;
            this.bunifuButton3.IconPadding = 10;
            this.bunifuButton3.IconRight = global::vista.Properties.Resources.refresh_10023535;
            this.bunifuButton3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton3.IconSize = 25;
            this.bunifuButton3.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton3.IdleBorderRadius = 0;
            this.bunifuButton3.IdleBorderThickness = 0;
            this.bunifuButton3.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton3.IdleIconLeftImage = null;
            this.bunifuButton3.IdleIconRightImage = global::vista.Properties.Resources.refresh_10023535;
            this.bunifuButton3.IndicateFocus = false;
            this.bunifuButton3.Location = new System.Drawing.Point(43, 342);
            this.bunifuButton3.Name = "bunifuButton3";
            this.bunifuButton3.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.OnDisabledState.BorderRadius = 1;
            this.bunifuButton3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnDisabledState.BorderThickness = 1;
            this.bunifuButton3.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.OnDisabledState.IconLeftImage = null;
            this.bunifuButton3.OnDisabledState.IconRightImage = null;
            this.bunifuButton3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.BorderRadius = 1;
            this.bunifuButton3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.onHoverState.BorderThickness = 1;
            this.bunifuButton3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.onHoverState.IconLeftImage = null;
            this.bunifuButton3.onHoverState.IconRightImage = null;
            this.bunifuButton3.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton3.OnIdleState.BorderRadius = 1;
            this.bunifuButton3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnIdleState.BorderThickness = 1;
            this.bunifuButton3.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton3.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton3.OnIdleState.IconLeftImage = null;
            this.bunifuButton3.OnIdleState.IconRightImage = global::vista.Properties.Resources.refresh_10023535;
            this.bunifuButton3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.BorderRadius = 1;
            this.bunifuButton3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnPressedState.BorderThickness = 1;
            this.bunifuButton3.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnPressedState.IconLeftImage = null;
            this.bunifuButton3.OnPressedState.IconRightImage = null;
            this.bunifuButton3.Size = new System.Drawing.Size(134, 39);
            this.bunifuButton3.TabIndex = 26;
            this.bunifuButton3.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton3.TextMarginLeft = 0;
            this.bunifuButton3.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton3.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButton2.ButtonText = "Borrar";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges2;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Roboto", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton2.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton2.IconLeft = null;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRight = global::vista.Properties.Resources.delete_10024167;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton2.IdleBorderRadius = 0;
            this.bunifuButton2.IdleBorderThickness = 0;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = global::vista.Properties.Resources.delete_10024167;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(199, 291);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 1;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.BorderRadius = 1;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.OnIdleState.BorderRadius = 1;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton2.OnIdleState.IconLeftImage = null;
            this.bunifuButton2.OnIdleState.IconRightImage = global::vista.Properties.Resources.delete_10024167;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 1;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(134, 39);
            this.bunifuButton2.TabIndex = 25;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            this.bunifuButton2.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Agregar";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges3;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.Empty;
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Roboto", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton1.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton1.IconLeft = null;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRight = global::vista.Properties.Resources.plus_10023487;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleBorderRadius = 0;
            this.bunifuButton1.IdleBorderThickness = 0;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.Empty;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = global::vista.Properties.Resources.plus_10023487;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(43, 291);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 1;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.BorderRadius = 1;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.OnIdleState.BorderRadius = 1;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = global::vista.Properties.Resources.plus_10023487;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 1;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(134, 39);
            this.bunifuButton1.TabIndex = 24;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            this.bunifuButton1.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // Pass_G
            // 
            this.Pass_G.AcceptsReturn = false;
            this.Pass_G.AcceptsTab = false;
            this.Pass_G.AnimationSpeed = 200;
            this.Pass_G.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Pass_G.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Pass_G.AutoSizeHeight = true;
            this.Pass_G.BackColor = System.Drawing.Color.Transparent;
            this.Pass_G.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Pass_G.BackgroundImage")));
            this.Pass_G.BorderColorActive = System.Drawing.Color.CornflowerBlue;
            this.Pass_G.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Pass_G.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Pass_G.BorderColorIdle = System.Drawing.Color.RoyalBlue;
            this.Pass_G.BorderRadius = 30;
            this.Pass_G.BorderThickness = 2;
            this.Pass_G.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Pass_G.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Pass_G.DefaultFont = new System.Drawing.Font("Roboto", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Pass_G.DefaultText = "";
            this.Pass_G.FillColor = System.Drawing.Color.White;
            this.Pass_G.HideSelection = true;
            this.Pass_G.IconLeft = null;
            this.Pass_G.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Pass_G.IconPadding = 10;
            this.Pass_G.IconRight = null;
            this.Pass_G.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Pass_G.Lines = new string[0];
            this.Pass_G.Location = new System.Drawing.Point(425, 207);
            this.Pass_G.MaxLength = 32767;
            this.Pass_G.MinimumSize = new System.Drawing.Size(1, 1);
            this.Pass_G.Modified = false;
            this.Pass_G.Multiline = false;
            this.Pass_G.Name = "Pass_G";
            stateProperties1.BorderColor = System.Drawing.Color.CornflowerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Pass_G.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Pass_G.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Pass_G.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.RoyalBlue;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Pass_G.OnIdleState = stateProperties4;
            this.Pass_G.Padding = new System.Windows.Forms.Padding(3);
            this.Pass_G.PasswordChar = '\0';
            this.Pass_G.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.Pass_G.PlaceholderText = "Conteaseña";
            this.Pass_G.ReadOnly = false;
            this.Pass_G.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Pass_G.SelectedText = "";
            this.Pass_G.SelectionLength = 0;
            this.Pass_G.SelectionStart = 0;
            this.Pass_G.ShortcutsEnabled = true;
            this.Pass_G.Size = new System.Drawing.Size(290, 49);
            this.Pass_G.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Pass_G.TabIndex = 23;
            this.Pass_G.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Pass_G.TextMarginBottom = 0;
            this.Pass_G.TextMarginLeft = 3;
            this.Pass_G.TextMarginTop = 1;
            this.Pass_G.TextPlaceholder = "Conteaseña";
            this.Pass_G.UseSystemPasswordChar = false;
            this.Pass_G.WordWrap = true;
            // 
            // Fecha_2
            // 
            this.Fecha_2.BackColor = System.Drawing.Color.Transparent;
            this.Fecha_2.BorderColor = System.Drawing.Color.Silver;
            this.Fecha_2.BorderRadius = 1;
            this.Fecha_2.Color = System.Drawing.Color.Silver;
            this.Fecha_2.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.Fecha_2.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.Fecha_2.DisabledColor = System.Drawing.Color.Gray;
            this.Fecha_2.DisplayWeekNumbers = false;
            this.Fecha_2.DPHeight = 0;
            this.Fecha_2.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.Fecha_2.FillDatePicker = false;
            this.Fecha_2.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Fecha_2.ForeColor = System.Drawing.Color.Black;
            this.Fecha_2.Icon = ((System.Drawing.Image)(resources.GetObject("Fecha_2.Icon")));
            this.Fecha_2.IconColor = System.Drawing.Color.Gray;
            this.Fecha_2.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.Fecha_2.LeftTextMargin = 5;
            this.Fecha_2.Location = new System.Drawing.Point(774, 137);
            this.Fecha_2.MinimumSize = new System.Drawing.Size(4, 32);
            this.Fecha_2.Name = "Fecha_2";
            this.Fecha_2.Size = new System.Drawing.Size(290, 32);
            this.Fecha_2.TabIndex = 22;
            this.Fecha_2.Value = new System.DateTime(2024, 9, 4, 0, 0, 0, 0);
            // 
            // Fecha_1
            // 
            this.Fecha_1.BackColor = System.Drawing.Color.Transparent;
            this.Fecha_1.BorderColor = System.Drawing.Color.Silver;
            this.Fecha_1.BorderRadius = 1;
            this.Fecha_1.Color = System.Drawing.Color.Silver;
            this.Fecha_1.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.Fecha_1.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.Fecha_1.DisabledColor = System.Drawing.Color.Gray;
            this.Fecha_1.DisplayWeekNumbers = false;
            this.Fecha_1.DPHeight = 0;
            this.Fecha_1.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.Fecha_1.FillDatePicker = false;
            this.Fecha_1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.Fecha_1.ForeColor = System.Drawing.Color.Black;
            this.Fecha_1.Icon = ((System.Drawing.Image)(resources.GetObject("Fecha_1.Icon")));
            this.Fecha_1.IconColor = System.Drawing.Color.Gray;
            this.Fecha_1.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.Fecha_1.LeftTextMargin = 5;
            this.Fecha_1.Location = new System.Drawing.Point(774, 68);
            this.Fecha_1.MinimumSize = new System.Drawing.Size(4, 32);
            this.Fecha_1.Name = "Fecha_1";
            this.Fecha_1.Size = new System.Drawing.Size(290, 32);
            this.Fecha_1.TabIndex = 21;
            this.Fecha_1.Value = new System.DateTime(2024, 9, 4, 0, 0, 0, 0);
            // 
            // Correo_G
            // 
            this.Correo_G.AcceptsReturn = false;
            this.Correo_G.AcceptsTab = false;
            this.Correo_G.AnimationSpeed = 200;
            this.Correo_G.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Correo_G.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Correo_G.AutoSizeHeight = true;
            this.Correo_G.BackColor = System.Drawing.Color.Transparent;
            this.Correo_G.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Correo_G.BackgroundImage")));
            this.Correo_G.BorderColorActive = System.Drawing.Color.CornflowerBlue;
            this.Correo_G.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Correo_G.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Correo_G.BorderColorIdle = System.Drawing.Color.RoyalBlue;
            this.Correo_G.BorderRadius = 30;
            this.Correo_G.BorderThickness = 2;
            this.Correo_G.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Correo_G.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Correo_G.DefaultFont = new System.Drawing.Font("Roboto", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Correo_G.DefaultText = "";
            this.Correo_G.FillColor = System.Drawing.Color.White;
            this.Correo_G.HideSelection = true;
            this.Correo_G.IconLeft = null;
            this.Correo_G.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Correo_G.IconPadding = 10;
            this.Correo_G.IconRight = null;
            this.Correo_G.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Correo_G.Lines = new string[0];
            this.Correo_G.Location = new System.Drawing.Point(425, 137);
            this.Correo_G.MaxLength = 32767;
            this.Correo_G.MinimumSize = new System.Drawing.Size(1, 1);
            this.Correo_G.Modified = false;
            this.Correo_G.Multiline = false;
            this.Correo_G.Name = "Correo_G";
            stateProperties5.BorderColor = System.Drawing.Color.CornflowerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Correo_G.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Correo_G.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Correo_G.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.RoyalBlue;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Correo_G.OnIdleState = stateProperties8;
            this.Correo_G.Padding = new System.Windows.Forms.Padding(3);
            this.Correo_G.PasswordChar = '\0';
            this.Correo_G.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.Correo_G.PlaceholderText = "Correo Electronico";
            this.Correo_G.ReadOnly = false;
            this.Correo_G.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Correo_G.SelectedText = "";
            this.Correo_G.SelectionLength = 0;
            this.Correo_G.SelectionStart = 0;
            this.Correo_G.ShortcutsEnabled = true;
            this.Correo_G.Size = new System.Drawing.Size(290, 49);
            this.Correo_G.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Correo_G.TabIndex = 18;
            this.Correo_G.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Correo_G.TextMarginBottom = 0;
            this.Correo_G.TextMarginLeft = 3;
            this.Correo_G.TextMarginTop = 1;
            this.Correo_G.TextPlaceholder = "Correo Electronico";
            this.Correo_G.UseSystemPasswordChar = false;
            this.Correo_G.WordWrap = true;
            // 
            // Apellido_2_G
            // 
            this.Apellido_2_G.AcceptsReturn = false;
            this.Apellido_2_G.AcceptsTab = false;
            this.Apellido_2_G.AnimationSpeed = 200;
            this.Apellido_2_G.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Apellido_2_G.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Apellido_2_G.AutoSizeHeight = true;
            this.Apellido_2_G.BackColor = System.Drawing.Color.Transparent;
            this.Apellido_2_G.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Apellido_2_G.BackgroundImage")));
            this.Apellido_2_G.BorderColorActive = System.Drawing.Color.CornflowerBlue;
            this.Apellido_2_G.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Apellido_2_G.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Apellido_2_G.BorderColorIdle = System.Drawing.Color.RoyalBlue;
            this.Apellido_2_G.BorderRadius = 30;
            this.Apellido_2_G.BorderThickness = 2;
            this.Apellido_2_G.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Apellido_2_G.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Apellido_2_G.DefaultFont = new System.Drawing.Font("Roboto", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Apellido_2_G.DefaultText = "";
            this.Apellido_2_G.FillColor = System.Drawing.Color.White;
            this.Apellido_2_G.HideSelection = true;
            this.Apellido_2_G.IconLeft = null;
            this.Apellido_2_G.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Apellido_2_G.IconPadding = 10;
            this.Apellido_2_G.IconRight = null;
            this.Apellido_2_G.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Apellido_2_G.Lines = new string[0];
            this.Apellido_2_G.Location = new System.Drawing.Point(425, 68);
            this.Apellido_2_G.MaxLength = 32767;
            this.Apellido_2_G.MinimumSize = new System.Drawing.Size(1, 1);
            this.Apellido_2_G.Modified = false;
            this.Apellido_2_G.Multiline = false;
            this.Apellido_2_G.Name = "Apellido_2_G";
            stateProperties9.BorderColor = System.Drawing.Color.CornflowerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Apellido_2_G.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Apellido_2_G.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Apellido_2_G.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.RoyalBlue;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Apellido_2_G.OnIdleState = stateProperties12;
            this.Apellido_2_G.Padding = new System.Windows.Forms.Padding(3);
            this.Apellido_2_G.PasswordChar = '\0';
            this.Apellido_2_G.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.Apellido_2_G.PlaceholderText = "Segundo Apellido";
            this.Apellido_2_G.ReadOnly = false;
            this.Apellido_2_G.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Apellido_2_G.SelectedText = "";
            this.Apellido_2_G.SelectionLength = 0;
            this.Apellido_2_G.SelectionStart = 0;
            this.Apellido_2_G.ShortcutsEnabled = true;
            this.Apellido_2_G.Size = new System.Drawing.Size(290, 49);
            this.Apellido_2_G.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Apellido_2_G.TabIndex = 17;
            this.Apellido_2_G.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Apellido_2_G.TextMarginBottom = 0;
            this.Apellido_2_G.TextMarginLeft = 3;
            this.Apellido_2_G.TextMarginTop = 1;
            this.Apellido_2_G.TextPlaceholder = "Segundo Apellido";
            this.Apellido_2_G.UseSystemPasswordChar = false;
            this.Apellido_2_G.WordWrap = true;
            // 
            // Apellido_1_G
            // 
            this.Apellido_1_G.AcceptsReturn = false;
            this.Apellido_1_G.AcceptsTab = false;
            this.Apellido_1_G.AnimationSpeed = 200;
            this.Apellido_1_G.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Apellido_1_G.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Apellido_1_G.AutoSizeHeight = true;
            this.Apellido_1_G.BackColor = System.Drawing.Color.Transparent;
            this.Apellido_1_G.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Apellido_1_G.BackgroundImage")));
            this.Apellido_1_G.BorderColorActive = System.Drawing.Color.CornflowerBlue;
            this.Apellido_1_G.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Apellido_1_G.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Apellido_1_G.BorderColorIdle = System.Drawing.Color.RoyalBlue;
            this.Apellido_1_G.BorderRadius = 30;
            this.Apellido_1_G.BorderThickness = 2;
            this.Apellido_1_G.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Apellido_1_G.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Apellido_1_G.DefaultFont = new System.Drawing.Font("Roboto", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Apellido_1_G.DefaultText = "";
            this.Apellido_1_G.FillColor = System.Drawing.Color.White;
            this.Apellido_1_G.HideSelection = true;
            this.Apellido_1_G.IconLeft = null;
            this.Apellido_1_G.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Apellido_1_G.IconPadding = 10;
            this.Apellido_1_G.IconRight = null;
            this.Apellido_1_G.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Apellido_1_G.Lines = new string[0];
            this.Apellido_1_G.Location = new System.Drawing.Point(43, 207);
            this.Apellido_1_G.MaxLength = 32767;
            this.Apellido_1_G.MinimumSize = new System.Drawing.Size(1, 1);
            this.Apellido_1_G.Modified = false;
            this.Apellido_1_G.Multiline = false;
            this.Apellido_1_G.Name = "Apellido_1_G";
            stateProperties13.BorderColor = System.Drawing.Color.CornflowerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Apellido_1_G.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Apellido_1_G.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Apellido_1_G.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.RoyalBlue;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Apellido_1_G.OnIdleState = stateProperties16;
            this.Apellido_1_G.Padding = new System.Windows.Forms.Padding(3);
            this.Apellido_1_G.PasswordChar = '\0';
            this.Apellido_1_G.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.Apellido_1_G.PlaceholderText = "Primer Apellido";
            this.Apellido_1_G.ReadOnly = false;
            this.Apellido_1_G.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Apellido_1_G.SelectedText = "";
            this.Apellido_1_G.SelectionLength = 0;
            this.Apellido_1_G.SelectionStart = 0;
            this.Apellido_1_G.ShortcutsEnabled = true;
            this.Apellido_1_G.Size = new System.Drawing.Size(290, 49);
            this.Apellido_1_G.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Apellido_1_G.TabIndex = 16;
            this.Apellido_1_G.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Apellido_1_G.TextMarginBottom = 0;
            this.Apellido_1_G.TextMarginLeft = 3;
            this.Apellido_1_G.TextMarginTop = 1;
            this.Apellido_1_G.TextPlaceholder = "Primer Apellido";
            this.Apellido_1_G.UseSystemPasswordChar = false;
            this.Apellido_1_G.WordWrap = true;
            // 
            // Nombre_G
            // 
            this.Nombre_G.AcceptsReturn = false;
            this.Nombre_G.AcceptsTab = false;
            this.Nombre_G.AnimationSpeed = 200;
            this.Nombre_G.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.Nombre_G.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.Nombre_G.AutoSizeHeight = true;
            this.Nombre_G.BackColor = System.Drawing.Color.Transparent;
            this.Nombre_G.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Nombre_G.BackgroundImage")));
            this.Nombre_G.BorderColorActive = System.Drawing.Color.CornflowerBlue;
            this.Nombre_G.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Nombre_G.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Nombre_G.BorderColorIdle = System.Drawing.Color.RoyalBlue;
            this.Nombre_G.BorderRadius = 30;
            this.Nombre_G.BorderThickness = 2;
            this.Nombre_G.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.Nombre_G.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.Nombre_G.DefaultFont = new System.Drawing.Font("Roboto", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Nombre_G.DefaultText = "";
            this.Nombre_G.FillColor = System.Drawing.Color.White;
            this.Nombre_G.HideSelection = true;
            this.Nombre_G.IconLeft = null;
            this.Nombre_G.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.Nombre_G.IconPadding = 10;
            this.Nombre_G.IconRight = null;
            this.Nombre_G.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.Nombre_G.Lines = new string[0];
            this.Nombre_G.Location = new System.Drawing.Point(43, 137);
            this.Nombre_G.MaxLength = 32767;
            this.Nombre_G.MinimumSize = new System.Drawing.Size(1, 1);
            this.Nombre_G.Modified = false;
            this.Nombre_G.Multiline = false;
            this.Nombre_G.Name = "Nombre_G";
            stateProperties17.BorderColor = System.Drawing.Color.CornflowerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Nombre_G.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.Nombre_G.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Nombre_G.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.RoyalBlue;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.Nombre_G.OnIdleState = stateProperties20;
            this.Nombre_G.Padding = new System.Windows.Forms.Padding(3);
            this.Nombre_G.PasswordChar = '\0';
            this.Nombre_G.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.Nombre_G.PlaceholderText = "Nombre";
            this.Nombre_G.ReadOnly = false;
            this.Nombre_G.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.Nombre_G.SelectedText = "";
            this.Nombre_G.SelectionLength = 0;
            this.Nombre_G.SelectionStart = 0;
            this.Nombre_G.ShortcutsEnabled = true;
            this.Nombre_G.Size = new System.Drawing.Size(290, 49);
            this.Nombre_G.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.Nombre_G.TabIndex = 15;
            this.Nombre_G.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.Nombre_G.TextMarginBottom = 0;
            this.Nombre_G.TextMarginLeft = 3;
            this.Nombre_G.TextMarginTop = 1;
            this.Nombre_G.TextPlaceholder = "Nombre";
            this.Nombre_G.UseSystemPasswordChar = false;
            this.Nombre_G.WordWrap = true;
            this.Nombre_G.TextChanged += new System.EventHandler(this.bunifuTextBox2_TextChanged);
            // 
            // ID_G
            // 
            this.ID_G.AcceptsReturn = false;
            this.ID_G.AcceptsTab = false;
            this.ID_G.AnimationSpeed = 200;
            this.ID_G.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.ID_G.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.ID_G.AutoSizeHeight = true;
            this.ID_G.BackColor = System.Drawing.Color.Transparent;
            this.ID_G.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ID_G.BackgroundImage")));
            this.ID_G.BorderColorActive = System.Drawing.Color.CornflowerBlue;
            this.ID_G.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ID_G.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.ID_G.BorderColorIdle = System.Drawing.Color.RoyalBlue;
            this.ID_G.BorderRadius = 30;
            this.ID_G.BorderThickness = 2;
            this.ID_G.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.ID_G.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.ID_G.DefaultFont = new System.Drawing.Font("Roboto", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.ID_G.DefaultText = "";
            this.ID_G.FillColor = System.Drawing.Color.White;
            this.ID_G.HideSelection = true;
            this.ID_G.IconLeft = null;
            this.ID_G.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.ID_G.IconPadding = 10;
            this.ID_G.IconRight = null;
            this.ID_G.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.ID_G.Lines = new string[0];
            this.ID_G.Location = new System.Drawing.Point(43, 68);
            this.ID_G.MaxLength = 32767;
            this.ID_G.MinimumSize = new System.Drawing.Size(1, 1);
            this.ID_G.Modified = false;
            this.ID_G.Multiline = false;
            this.ID_G.Name = "ID_G";
            stateProperties21.BorderColor = System.Drawing.Color.CornflowerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ID_G.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.ID_G.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ID_G.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.RoyalBlue;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.ID_G.OnIdleState = stateProperties24;
            this.ID_G.Padding = new System.Windows.Forms.Padding(3);
            this.ID_G.PasswordChar = '\0';
            this.ID_G.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.ID_G.PlaceholderText = "ID";
            this.ID_G.ReadOnly = true;
            this.ID_G.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.ID_G.SelectedText = "";
            this.ID_G.SelectionLength = 0;
            this.ID_G.SelectionStart = 0;
            this.ID_G.ShortcutsEnabled = true;
            this.ID_G.Size = new System.Drawing.Size(290, 49);
            this.ID_G.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.ID_G.TabIndex = 14;
            this.ID_G.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.ID_G.TextMarginBottom = 0;
            this.ID_G.TextMarginLeft = 3;
            this.ID_G.TextMarginTop = 1;
            this.ID_G.TextPlaceholder = "ID";
            this.ID_G.UseSystemPasswordChar = false;
            this.ID_G.WordWrap = true;
            // 
            // Gestion
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1141, 988);
            this.Controls.Add(this.materialTabControl1);
            this.DrawerTabControl = this.materialTabControl1;
            this.Name = "Gestion";
            this.Text = "Gestion";
            this.Load += new System.EventHandler(this.Gestion_Load);
            this.materialTabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            this.materialCard1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.MyDataUsers)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private MaterialSkin.Controls.MaterialTabControl materialTabControl1;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.TabPage tabPage2;
        private Bunifu.UI.WinForms.BunifuDataGridView MyDataUsers;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private MaterialSkin.Controls.MaterialCard materialCard1;
        private Bunifu.UI.WinForms.BunifuTextBox Pass_G;
        private Bunifu.UI.WinForms.BunifuDatePicker Fecha_2;
        private Bunifu.UI.WinForms.BunifuDatePicker Fecha_1;
        private MaterialSkin.Controls.MaterialComboBox Empleados_G;
        private MaterialSkin.Controls.MaterialComboBox Generos_G;
        private Bunifu.UI.WinForms.BunifuTextBox Correo_G;
        private Bunifu.UI.WinForms.BunifuTextBox Apellido_2_G;
        private Bunifu.UI.WinForms.BunifuTextBox Apellido_1_G;
        private Bunifu.UI.WinForms.BunifuTextBox Nombre_G;
        private Bunifu.UI.WinForms.BunifuTextBox ID_G;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton3;
    }
}